### ISSUE TITLE
效果太差了！

### ISSUE THREAD

**Issue by joshualeung** [sing1ee/simhash-java#4]
用得不放心啊，相同的词语，只是变个顺序，simhash的距离居然能到10。

**Comment by joshualeung** [comment]
在另一个simhash实现上的测试是100%相似。
![image](https://cloud.githubusercontent.com/assets/1674024/12107140/e1567296-b3a1-11e5-8cc9-8adaf36328ad.png)

**Comment by sing1ee** [comment]
@joshualeung 多谢反馈，方便给一个你哪个simhash实现的链接？这个与具体实现相关的。谢谢。

**Comment by sing1ee** [comment]
@joshualeung 我看了一下，应该是分词方法的问题。你用的是哪个呢？如果是默认的，是bigram分词。先后顺序是有关系的，而且影响会比较大。

**Comment by joshualeung** [comment]
多谢回复！
我对比用的是这个实现: http://aneurone.blogspot.com/2012/09/simhash.html
demo在这里: http://aneuroneblog.appspot.com/demo/simhash.html
看了下源码实现，这个版本的比较通用，但使用起来稍麻烦，demo里应该是把字符串拆成一个个的字了，没有考虑顺序的问题。如果使用bigram， 顺序确实会有些影响。
